// Datos de contenido para cada imagen Open Graph (1200x630).
// Cada entrada alimenta scripts/og/template.html vía scripts/og/generate.mjs.

export const sections = [
  {
    slug: 'default',
    kicker: '/',
    kickerLabel: 'DISPONIBLE · COLOMBIA · REMOTO',
    titleLine1: 'CodeByMike',
    titleLine2: 'Senior Software Engineer',
    description: 'TypeScript · React · Next.js · Astro · Node.js · PostgreSQL',
    footerLeft: 'codebymike.tech',
    footerRight: 'github.com/mikerb95',
    ornament: 'brand',
  },
  {
    slug: 'status',
    kicker: '/STATUS',
    kickerLabel: 'TRANSPARENCIA OPERACIONAL',
    titleLine1: 'Estado de los servicios,',
    titleLine2: 'medido, no prometido.',
    description: 'Uptime, latencia y presupuesto de error de cada servicio que opero — datos en vivo de mi propia infraestructura de monitoreo.',
    badge: 'SLO 99.5% · ventana 30 días',
    ornament: 'bars',
  },
  {
    slug: 'tools',
    kicker: '/TOOLS',
    kickerLabel: 'HERRAMIENTAS PÚBLICAS',
    titleLine1: 'Utilidades que construí',
    titleLine2: 'para resolver problemas reales.',
    description: 'Pequeñas herramientas gratuitas, sin fricción, que uso yo mismo en el día a día.',
    ornament: 'grid',
  },
  {
    slug: 'engineering',
    kicker: '/ENGINEERING',
    kickerLabel: 'CÓMO CONSTRUYO',
    titleLine1: 'Decisiones de ingeniería,',
    titleLine2: 'explicadas con evidencia.',
    description: 'Arquitectura, trade-offs y el razonamiento detrás de cada sistema que diseño y opero.',
    ornament: 'architecture',
  },
  {
    slug: 'notes',
    kicker: '/NOTES',
    kickerLabel: 'APUNTES TÉCNICOS',
    titleLine1: 'Notas de ingeniería,',
    titleLine2: 'escritas mientras construyo.',
    description: 'Aprendizajes, bugs curiosos y decisiones documentadas en el momento, no meses después.',
    ornament: 'prose',
  },
  {
    slug: 'security',
    kicker: '/SECURITY',
    kickerLabel: 'DEFENSA ACTIVA',
    titleLine1: 'Seguridad del sitio,',
    titleLine2: 'vigilada, no asumida.',
    description: 'Cabeceras, monitoreo, respuesta a incidentes y el micro-SIEM que registra cada intento sospechoso.',
    ornament: 'log',
  },
  {
    slug: 'certifications',
    kicker: '/CERTIFICATIONS',
    kickerLabel: 'CREDENCIALES',
    titleLine1: 'Certificaciones,',
    titleLine2: 'verificables, no decorativas.',
    description: 'Cada credencial enlaza a su verificación oficial — nada de insignias sin respaldo.',
    ornament: 'badges',
  },
  {
    slug: 'log',
    kicker: '/LOG',
    kickerLabel: 'BITÁCORA',
    titleLine1: 'Registro de cambios,',
    titleLine2: 'commit a commit.',
    description: 'Qué cambió, cuándo y por qué — la historia real del proyecto, sin editar.',
    ornament: 'commits',
  },
  {
    slug: 'contact',
    kicker: '/CONTACT',
    kickerLabel: 'DISPONIBLE AHORA',
    titleLine1: 'Hablemos,',
    titleLine2: 'sin intermediarios.',
    description: 'Un mensaje directo, sin formularios eternos ni bandejas de reclutamiento.',
    ornament: 'available',
  },
]
